spring:
  security:
    oauth2:
      client:
        registration:
          client:
            client-id: client
            client-secret: "{noop}noop-secret"
            authorization-grant-type: client_credentials
            scope: read, write
            provider: default  # Referencing the provider below
        provider:
          default:
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token  # Ensure the correct endpoint here


logging:
  level:
    org.springframework.security: DEBUG  # Enable DEBUG level logging for security-related information
